name: CI

on: [push, pull_request]

jobs:
  CI:
    name: Launching CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-developer.txt
          pip install optuna==4.0.0 xgboost==2.1.2 scikit-learn==1.5.2 pydantic==2.4.2 numpy==1.24.0
      - name: Run Pre commit hook (formatting, linting & tests)
        run: pre-commit run --all-files --hook-stage pre-push --show-diff-on-failure
      - name: run unit tests
        run: pytest tests/